[features]
seeds = false
skip-lint = false
[programs.localnet]
test = "2PJhBWrBAUhsNrrN9R7o7Yz7BzykCdhrdMpEgjee8BrT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/qwexd/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
my-custom-script = "echo 'Hello, world!'"
